export * from './PastilleParcoursDefault';
export * from './PastilleParcoursVariant2';
export * from './PastilleParcoursVariant3';
export * from './IlotMenu';
export * from './Menu';
export * from './MenuButton';
export * from './RightArrow';
export * from './Icon';
export * from './QuizOff';
export { default as ProfilV2 } from './ProfilV2';
export { default as HomeV2 } from './HomeV2';
export { default as CataV2 } from './CataV2';
export { default as LabV2 } from './LabV2';
export { default as BoutiqueV2 } from './BoutiqueV2'; 